name: Prueba

on:
  push:
    branches:
      - master

jobs:
  Saludar:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Hola mundo"
      - run: echo "Chau mundo"
  Mostrar_Hora:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "La hora es $(date)"
  Mostrar_ubicacion:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          curl ipinfo.io

