name: Schedule Pipeline Example

on:
  schedule:
    - cron: "*/5 * * * *" # This is every 5 minutes
    # - cron: '0 1 * * *' # This is 1 AM every day
    # - cron: '0 2 * * *' # This is 2 AM every day
    # - cron: '30 5 15 * *'
    # - cron: '* 12 * * *'
    # - cron: '* * * * 3'
    # - cron: '0 10 * * 0'
    # - cron: '0 9-18 * * 1-5'
    # - cron: '*/15 17 * * 1,3'
    # - cron: '0 0 */2 * *'

    # * * * * *  Minutos Horas Días Meses Dia_de_la_semana

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl ipinfo.io
      - run: echo "La hora es $(date)"
